### ISSUE TITLE
CTK error with contents in target folder 

### ISSUE THREAD

**Issue by MollyZhang** [wstidolph/ctk-core#20]
if target folder is empty, ctk -u works
if there is content in target folder, this error occurs:
`date: illegal option -- I`
`usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... `
`            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]`
`>> ERROR: 1`
`>> ./ctk 106 on_err`

**Comment by wstidolph** [comment]
Being inux-centric, the current ctk script uses GNU utilities, and specifically it uses `date -Iseconds` to form the new name for the target directory; sadly, Mac OS X *doesn't* use GNU coreutils (I didn't know this). I guess we have a couple options -

(1) abandon using `date` to rename the old test runs and come up with some other scheme; or,
(2) require mac users to install gnu stuff (`brew install coreutils`) and link in that `date`; or,
(3) rewrite the script to use something common to OS X's version of date and the linux (GNU) version of date, or
(4) tell Mac user's they're out of luck :) and have to use `java` directly

I'll look into (3) first, see if there's something simple we can do that will "just work" on gnu bash and on OS X cmd line.

**Comment by wstidolph** [comment]
fixed in alpha.5
