### ISSUE TITLE
Drop API divisions?

### ISSUE THREAD

**Issue by wstidolph** [wstidolph/ctk-core#26]
Recent discussion in issue #25 indicates maybe the original division of communications and tests by API was naive ... should we fix that?

The cts-java tests are split into java packages by API- there's a reads package, a reference package, a variants package (and a 'core' package). Given a more "unified" view of the tests, perhaps we should do away with that distinction? Further there are then "ReadsTest" etc TestSuites/categories so a dev can run just the Reads tests, etc. but can we come up with more meaningful groupings/categories than just by the API?

**Comment by diekhans** [comment]
Wayne Stidolph <notifications@github.com> writes:
> Recent discussion in issue #25 indicates maybe the original division of
> communications and tests by API was naive ... should we fix that?

Division of tests by API is a good for the basic approach, as
long it isn't restrictive for adding tests that are group in
other ways.  Also higher level APIs need to be able to compose
tests using multiple, lower-level APIs.

Please explain (i.e. point to docs) what you mean by "division
of communications".

I am only asking for clarity, not something to be done different.

**Comment by wstidolph** [comment]
I meant that the communication layer had a different ProtocolClient class
for each API ... ReadProtocolClient, VariantProtocolClient, etc

**Comment by diekhans** [comment]
Wayne Stidolph <notifications@github.com> writes:
> I meant that the communication layer had a different ProtocolClient class
> for each API ... ReadProtocolClient, VariantProtocolClient, etc

As long as you can mix and match them in the tests, this seems
very logical.  One-to-one mapping to the components of the API.

I think this is great.

**Comment by hjellinek** [comment]
In practice I found it unworkable.  The API isn't so large (only 10 distinct operations) that this sort of division is helpful.  Moreover, it isn't a division that's immediately obvious to the would-be user, because most typical higher-level operations (and therefore tests) had to span multiple "client" objects.  Having to remember which one, then instantiate it and call it, clutters the code and raises the bar on the basic Java knowledge a test-writer needs to have.

**Comment by wstidolph** [comment]
It's an interesting design choice - I see Herb's experience as very
important (our only *real* test-writer experience so far), but the server
is still in it'ssmaller stages ... as the server gains more methods and
APIs, a unified Client can become a problem. A "God Object" model (all the
API on one surface) makes it more difficult to write test stubs and mocks,
and I can see the unified approach complicating the life of someone who's
trying to evolve just one API. So there's a design tension here, are we
designing for the first user and tests (Herb/Cassie's tests), or should we
be envisioning something else and trying to design towards that?

Part of this all stems from a vagueness (for me, at least) on "what is an
API" in the discussions of using the CTK to support an API-designer, and
wanting to keep as small as possible the code in front of that API designer.

As a *practical* matter, I've merged Herb's changes (the unified Client) on
the 'develop' branch.  Also, on the 'servermode' branch I've further folded
in my updates to get rid of a global "URLMAPPING" object. I'm trying to get
the Client layer to be more test-friendly, so we can stub it off when
making the transition to a different target server or transport protocol
(binary vs JSON/HTTP).

On Tue, Jul 21, 2015 at 8:48 AM, Herb Jellinek <notifications@github.com>
wrote:

> In practice I found it unworkable. The API isn't so large (only 10
> distinct operations) that this sort of division is helpful. Moreover, it
> isn't a division that's immediately obvious to the would-be user, because
> most typical higher-level operations (and therefore tests) had to span
> multiple "client" objects. Having to remember which one, then instantiate
> it and call it, clutters the code and raises the bar on the basic Java
> knowledge a test-writer needs to have.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wstidolph/ctk-core/issues/26#issuecomment-123380652>.
>



-- 
  Wayne Stidolph  | (831) 419 7146 | LinkedIn
<http://www.linkedin.com/in/waynestidolph> | Google+
<https://google.com/+WayneStidolph> | twitter
<https://twitter.com/#!/wstidolph> | personal blog
<http://waynedge.blogspot.com/>

**Comment by hjellinek** [comment]
As I may have mentioned in an earlier note, splitting the Client object 
later would be trivial.  But using the multiple -Client objects was a 
pain.  Cassie's tests were/are much more concise than what I found 
myself writing, in part because she was able to skip creating even a 
single interface object.  That's not an attractive approach in our case, 
I believe, but I can live with a single one. More than that and I have 
to think (see e.g. Steve Krug's Don't Make Me Think 
<https://en.wikipedia.org/wiki/Don%27t_Make_Me_Think> for why that's 
bad. :-))

                 Herb

**Comment by wstidolph** [comment]
So, I opened this issue to ask a question I'm still waiting for an opinion
on ... if it's good to ignore the divisions in the communication layer
(unified Client) then should we be ignore that division in the test
groupings?

We have the tests grouped by "API" (as I understood it). So, if you're
writing a test that needs access to more than one communications API, what
package does that test belong in? Should we drop all packaging and just
have tests in one bucket, maybe make a better use of Categories? Or are
there some functional grouping of tests which make sense?

(BTW, where did you put "Cassie's tests"? I'd like to look at what they
needed ...)

On Tue, Jul 21, 2015 at 9:06 AM, Herb Jellinek <notifications@github.com>
wrote:

> As I may have mentioned in an earlier note, splitting the Client object
> later would be trivial. But using the multiple -Client objects was a
> pain. Cassie's tests were/are much more concise than what I found
> myself writing, in part because she was able to skip creating even a
> single interface object. That's not an attractive approach in our case,
> I believe, but I can live with a single one. More than that and I have
> to think (see e.g. Steve Krug's Don't Make Me Think
> <https://en.wikipedia.org/wiki/Don%27t_Make_Me_Think> for why that's
> bad. :-))
>
> Herb
>
>
> On 7/21/15 8:57 AM, Wayne Stidolph wrote:
> > It's an interesting design choice - I see Herb's experience as very
> > important (our only *real* test-writer experience so far), but the server
> > is still in it'ssmaller stages ... as the server gains more methods and
> > APIs, a unified Client can become a problem. A "God Object" model (all
> the
> > API on one surface) makes it more difficult to write test stubs and
> mocks,
> > and I can see the unified approach complicating the life of someone who's
> > trying to evolve just one API. So there's a design tension here, are we
> > designing for the first user and tests (Herb/Cassie's tests), or should
> we
> > be envisioning something else and trying to design towards that?
> >
> > Part of this all stems from a vagueness (for me, at least) on "what is an
> > API" in the discussions of using the CTK to support an API-designer, and
> > wanting to keep as small as possible the code in front of that API
> > designer.
> >
> > As a *practical* matter, I've merged Herb's changes (the unified
> > Client) on
> > the 'develop' branch. Also, on the 'servermode' branch I've further
> folded
> > in my updates to get rid of a global "URLMAPPING" object. I'm trying
> > to get
> > the Client layer to be more test-friendly, so we can stub it off when
> > making the transition to a different target server or transport protocol
> > (binary vs JSON/HTTP).
> >
> > On Tue, Jul 21, 2015 at 8:48 AM, Herb Jellinek <notifications@github.com
> >
> > wrote:
> >
> > > In practice I found it unworkable. The API isn't so large (only 10
> > > distinct operations) that this sort of division is helpful. Moreover,
> it
> > > isn't a division that's immediately obvious to the would-be user,
> > because
> > > most typical higher-level operations (and therefore tests) had to span
> > > multiple "client" objects. Having to remember which one, then
> > instantiate
> > > it and call it, clutters the code and raises the bar on the basic Java
> > > knowledge a test-writer needs to have.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > >
> > <https://github.com/wstidolph/ctk-core/issues/26#issuecomment-123380652
> >.
> > >
> >
> >
> >
> > --
> > Wayne Stidolph | (831) 419 7146 | LinkedIn
> > <http://www.linkedin.com/in/waynestidolph> | Google+
> > <https://google.com/+WayneStidolph> | twitter
> > <https://twitter.com/#!/wstidolph> | personal blog
> > <http://waynedge.blogspot.com/>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/wstidolph/ctk-core/issues/26#issuecomment-123384013
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wstidolph/ctk-core/issues/26#issuecomment-123386480>.
>



-- 
  Wayne Stidolph  | (831) 419 7146 | LinkedIn
<http://www.linkedin.com/in/waynestidolph> | Google+
<https://google.com/+WayneStidolph> | twitter
<https://twitter.com/#!/wstidolph> | personal blog
<http://waynedge.blogspot.com/>

**Comment by diekhans** [comment]
Examples please

-- Sent from my computer phone

-----Original Message-----

**Comment by hjellinek** [comment]
The current Compliance repo ("Cassie's tests") is ga4gh/compliance.  The tests are in a single file, v0.5tests.js.  I had to make the changes to the CTK to remove some obstacles that were preventing me from converting the v0.5tests.js tests to Java.  That is still in progress... next up, I need to sync the schemas.  The subject, no doubt, of another discussion.

**Comment by diekhans** [comment]
Cassie test are not very deep so I don't know how good a model they are

-- Sent from my computer phone

-----Original Message-----

**Comment by wstidolph** [comment]
Yes, I know where the current tests are - I mean, what does your java
re-casting look like, since that's what's going to show us something about
the CTK approaches. The only obstacles I remembered in re-implementing
those tests (I played with but didn't check in) was setting up the
different target servers in one test, and that IIRC they were using APIs
and data which I didn't have on the Ref Server, so I dropped that migration
for the moment.

On Tue, Jul 21, 2015 at 9:20 AM, Herb Jellinek <notifications@github.com>
wrote:

> The current Compliance repo ("Cassie's tests") is ga4gh/compliance. The
> tests are in a single file, v0.5tests.js. I had to make the changes to the
> CTK to remove some obstacles that were preventing me from converting the
> v0.5tests.js tests to Java. That is still in progress... next up, I need to
> sync the schemas. The subject, no doubt, of another discussion.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wstidolph/ctk-core/issues/26#issuecomment-123390759>.
>



-- 
  Wayne Stidolph  | (831) 419 7146 | LinkedIn
<http://www.linkedin.com/in/waynestidolph> | Google+
<https://google.com/+WayneStidolph> | twitter
<https://twitter.com/#!/wstidolph> | personal blog
<http://waynedge.blogspot.com/>

**Comment by hjellinek** [comment]
My Java recasting looks like the caricature I posted in the commit message.  Here's another:

```
private static Client client = new Client();

@Test
public void searchReadGroupSets() {
    ...
    client.doThis();
    assertThat(...)...;
    client.doThat();
    assertThat(...)...;
}

```

Pretty much as you'd expect.

**Comment by wstidolph** [comment]
(Going meta on you here, Mark)

I'm not clear what you are looking for an example of... do you have an
example?

The current develop-branch test groupings are visible under
https://github.com/wstidolph/ctk-core/tree/servermode/cts-java/src/test/java/org/ga4gh/cts/api.
You'll see packages for reads, variants, references (since those were the
*methods.avdl files). I was just extending the IDL forward to the protocol
clients and the test groupings, it's no smarter than that.

In those tests, the difference is going to be mainly that when the
test-writer sets up the Client (a once-per-test-class task) they use, e.g.,
"new Client()" rather than "new VariantsProtocolClient()"



On Tue, Jul 21, 2015 at 9:15 AM, Mark Diekhans <notifications@github.com>
wrote:

> Examples please
>
> -- Sent from my computer phone
>
>
> -----Original Message-----
> From: Wayne Stidolph <notifications@github.com>
> To: wstidolph/ctk-core <ctk-core@noreply.github.com>
> Cc: Mark Diekhans <markd@soe.ucsc.edu>
> Sent: Tue, 21 Jul 2015 4:58 PM
> Subject: Re: [ctk-core] Drop API divisions? (#26)
>
> It's an interesting design choice - I see Herb's experience as very
> important (our only *real* test-writer experience so far), but the server
> is still in it'ssmaller stages ... as the server gains more methods and
> APIs, a unified Client can become a problem. A "God Object" model (all the
> API on one surface) makes it more difficult to write test stubs and mocks,
> and I can see the unified approach complicating the life of someone who's
> trying to evolve just one API. So there's a design tension here, are we
> designing for the first user and tests (Herb/Cassie's tests), or should we
> be envisioning something else and trying to design towards that?
>
> Part of this all stems from a vagueness (for me, at least) on "what is an
> API" in the discussions of using the CTK to support an API-designer, and
> wanting to keep as small as possible the code in front of that API
> designer.
>
> As a *practical* matter, I've merged Herb's changes (the unified Client) on
> the 'develop' branch. Also, on the 'servermode' branch I've further folded
> in my updates to get rid of a global "URLMAPPING" object. I'm trying to get
> the Client layer to be more test-friendly, so we can stub it off when
> making the transition to a different target server or transport protocol
> (binary vs JSON/HTTP).
>
> On Tue, Jul 21, 2015 at 8:48 AM, Herb Jellinek <notifications@github.com>
> wrote:
>
> > In practice I found it unworkable. The API isn't so large (only 10
> > distinct operations) that this sort of division is helpful. Moreover, it
> > isn't a division that's immediately obvious to the would-be user, because
> > most typical higher-level operations (and therefore tests) had to span
> > multiple "client" objects. Having to remember which one, then instantiate
> > it and call it, clutters the code and raises the bar on the basic Java
> > knowledge a test-writer needs to have.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/wstidolph/ctk-core/issues/26#issuecomment-123380652
> >.
> >
>
>
>
> --
> Wayne Stidolph | (831) 419 7146 | LinkedIn
> <http://www.linkedin.com/in/waynestidolph> | Google+
> <https://google.com/+WayneStidolph> | twitter
> <https://twitter.com/#!/wstidolph> | personal blog
> <http://waynedge.blogspot.com/>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/wstidolph/ctk-core/issues/26#issuecomment-123384013
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wstidolph/ctk-core/issues/26#issuecomment-123389456>.
>



-- 
  Wayne Stidolph  | (831) 419 7146 | LinkedIn
<http://www.linkedin.com/in/waynestidolph> | Google+
<https://google.com/+WayneStidolph> | twitter
<https://twitter.com/#!/wstidolph> | personal blog
<http://waynedge.blogspot.com/>

**Comment by diekhans** [comment]
Pointers to ctk client and ported code is what I need...

-- Sent from my computer phone

-----Original Message-----

**Comment by wstidolph** [comment]
That caricature doesn't tell us anything specific, though. We really should
be specific about what Cassie's tests need (even if they're not deep) ...
I'm loking forward to your java re-casting!

On Tue, Jul 21, 2015 at 9:28 AM, Herb Jellinek <notifications@github.com>
wrote:

> My Java recasting looks like the caricature I posted in the commit
> message. Here's another:
>
> private static Client client = new Client();
>
> @Test
> public void searchReadGroupSets() {
>     ...
>     client.doThis();
>     assertThat(...)...;
>     client.doThat();
>     assertThat(...)...;
> }
>
>
> Pretty much as you'd expect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wstidolph/ctk-core/issues/26#issuecomment-123393288>.
>



-- 
  Wayne Stidolph  | (831) 419 7146 | LinkedIn
<http://www.linkedin.com/in/waynestidolph> | Google+
<https://google.com/+WayneStidolph> | twitter
<https://twitter.com/#!/wstidolph> | personal blog
<http://waynedge.blogspot.com/>

**Comment by hjellinek** [comment]
I'm working on the ported code in another branch, not yet pushed.  This work was a prerequisite.

**Comment by diekhans** [comment]
What is an API is kind of an unimportant questions.  the whole think is
the GA4GH API and it has sub-APIs for specific functional areas.

It's good for molecularity and maintainability to not have one
god class that has everything in it.

It's also annoying to carry around five objects to implement
tests.  Plus, to be a realistic test, they should, most of the
time, share the same connection.

I think an explicit container that reflects the API is the right
approach.

So you would have something like:
   client.reads.search(xxx)  // or what ever the component API.


It's suppose to be an integrated API, so when you write tests,
for say variants, you still will need to touch other pieces,
like reads.

I don't think this is an either/or thing.

Mark
