### ISSUE TITLE
make servermode test classes dir a property

### ISSUE THREAD

**Issue by wstidolph** [wstidolph/ctk-core#27]
Use case - test developer has an IDE or workflow putting cts-java test classes into directories A, B, C, ... they edit a test, recompile their test suite and want to run the tests. They can use the IDE's built-in JUnit runner, but if they want to run under the CTK (with out a full package/install) then this would let them set a property ctk.testclassdirs="A,B,C", launch the server option, and just hit a browser refresh when they wanted a test report.

The ctk.testclassdirs property would be comma-split and added as pathelement locations (antRunTests.xml approx line 25 right now, but probably turned into a classpath/refid with this effort). Then, whenever the developer runs the tests (browser refresh, etc) ant picks up the new .class files.

**Comment by diekhans** [comment]
isn't a path directoies normally `:' separated?

**Comment by wstidolph** [comment]
Well, that's a good point ... using normal path notation should make it much simpler to use as well as write!

**Comment by wstidolph** [comment]
And, it turns out Ant will do the path-splitting for us if we use normal notations ... using a normal colon or semi-colon separated path (`ctk.testclassdirs="a:b:c"`)

it looks to be just a one-liner change in the antRunTests.xml:25, from

    <pathelement location="target/test-classes"/>
to

     <pathelement path="${ctk.testclassdirs}"/>

I need to look at whether this has any impact in ctk-cli (and ctk-server) but it looks like a nice bit of flexibility.

**Comment by wstidolph** [comment]
Well, nothing is ever a one-liner. I tried the obvious (using multirootfileset) but that (a) triggers the xml formatter to send an annoying error message to system err (the message is correct that "class" isn't a "jar" but who cares?); and (b) doesn't seem to run the tests because of (a) thus no tests run even though tests are on the classpath, and so the junitreport task seems to throw a NullPointterException. So, I'm dropping this "quick" task for the moment ... here (for reference) is the code I used in the antRunTests.xml build file (along with the obvious proprty capture/pass in application.properties and in Props.java)

```xml
<junit printsummary="on" fork="off" filtertrace="on"
               haltonfailure="false" showoutput="true">
            <classpath>
                <fileset dir="lib">
                    <include name="**/*.jar"/>
                </fileset>
                <multirootfileset basedirs="${ctk.testclasspath}" includes="${ctk.matchstr}"
                                  erroronmissingdir="false"/>
                <pathelement location="target/test-classes"/>
            </classpath>
            <batchtest fork="off" todir="${ctk.todir}" skipNonTests="true">
                <!-- the multirootfileset inside batchtest is triggering system.out.println from Ant's ClassLoader of
                "CLASSPATH element... is not a JAR" to system 'err' (which is a true statement) -->
                <!-- happens whether we have the zipfileset commented out, or no jar file, or
                     even if zipfileset is OK, runs tests -->
                <!-- error is coming *after* the Test classes are properly found and queued, when
                     the xml formatter is being built (on every test) -->
                <!-- then, since no XML files are built, we get a NPE frm the junitreports task! -->
                <multirootfileset basedirs="${ctk.testclasspath}" includes="${ctk.matchstr}"
                                  erroronmissingdir="false"/>
                <zipfileset src="lib/${ctk.testjar}" includes="${ctk.matchstr}"
                            erroronmissingarchive="false"/>
            </batchtest>
            <formatter type="xml"/>
            <formatter type="brief"/>
            <!-- this "formatter" just bridges junit events to the CTK log -->
            <formatter classname="org.ga4gh.ctk.TestExecListener"/>
        </junit>
    </target>
```

**Comment by wstidolph** [comment]
Closing as not-active/deferred (github workflow is too simplistic)
