### ISSUE TITLE
Show how to configure just one test class, by duplicating "Google" compliance tests

### ISSUE THREAD

**Issue by wstidolph** [wstidolph/ctk-core#6]
The existing javascript tests should be migrated into the java-based CTS. Since those tests are human "choose target" driven, there needs to be a test-specific property to select the server to target; so, this effort includes the design problem of setting CTS convention for "how to control a specific test class"

**Comment by wstidolph** [comment]
Capturing an interim thought - I'm thinking we provide a utility function on the existing Props object, one which takes a string and returns all the properties with the name "cts.<the string>" bound into a flat Properties object. The class could use its name, whatever:

    Properties myprops = Props.fetch("ReadMethodsIT");

and get back a Properties with, e.g.,

```java
cts.ReadMethodsIT.silly=foo
cts.ReadMethodsIT.silly.2=bar
cts.ReadMethodsIT.silly.3=zig
```

As a convenience, we could also provide an iterator over the Properties based on a subfield extraction (the .2, .3 above). But, then we ought to come up with a Provider to use with the @Parameters annotation so that subfields can drive properties into individual test cases.

**Comment by wstidolph** [comment]
Assigning over to Herb since he's already pondering how to bring the Google tests into the CTK.

**Comment by hjellinek** [comment]
I converted the Google tests long ago; this item is essentially a duplicate/forerunner of [this one](https://github.com/ga4gh/compliance/issues/43).
